<?php 

//// BOT keys 
$BOT_TOKEN = "the_bot_token";
$BOT_NAME = "the_bot_name";
$DB_NAME = "the_bot_db_name";
$DB_USER = "the_bot_db_user";
$DB_PASSWORD = "the_bot_db_password";



//1xx Azione normale
//2xx Azione illecita
//3xx Errore interno

//0 start
//1 privacy
//2 name
//3 point
//4 stop
//5 content
//6 validate



define ('SET_LANGUAGE_REQUEST', 100);
define ('SET_LANGUAGE_CHOICE_EN', 101);
define ('SET_LANGUAGE_CHOICE_IT', 102);

define ('CREATE_TRACK_CHOICE_SET_TRACK_PRIVACY_REQUEST', 103);

define ('SET_PRIVATE_TRACK_CHOICE_SET_TRACK_NAME_REQUEST', 104);
define ('SET_PUBLIC_TRACK_CHOICE_SET_TRACK_NAME_REQUEST', 105);

define ('SET_TRACK_NAME_REQUEST', 106);
define ('SET_IMPLICIT_TRACK_NAME_CHOICE', 107);
define ('SET_FIRST_TRACK_NAME_CHOICE', 108);
define ('SET_TRACK_NAME_CHOICE', 109);

define ('SET_PRIVATE_TRACK_CHOICE', 110);
define ('SET_PUBLIC_TRACK_CHOICE', 111);

define ('CREATE_FIRST_TRACKPOINT_CHOICE_SET_TAG_REQUEST', 112);
define ('CREATE_TRACKPOINT_CHOICE_SET_TAG_REQUEST', 113);
define ('CREATE_LATE_TRACKPOINT_CHOICE_SET_TAG_REQUEST', 114);
define ('SET_TAG_REQUEST', 115);

define ('FILE_CHOICE', 116);
define ('LATE_FILE_CHOICE', 117);

define ('SET_TAG_DANGER_CHOICE_SET_TRACK_PRIVACY_REQUEST', 118);
define ('SET_TAG_POI_CHOICE_SET_TRACK_PRIVACY_REQUEST', 119);
define ('SET_TAG_GENERIC_CHOICE_SET_TRACK_PRIVACY_REQUEST', 120);
define ('SET_TAG_DANGER_CHOICE', 121);
define ('SET_TAG_POI_CHOICE', 122);
define ('SET_TAG_GENERIC_CHOICE', 123);
define ('VIEW_TRACK_CHOICE', 124);

define ('SHOW_MAP_CHOICE', 125);

define ('END_TRACK_CHOICE_OVERHAUL_REQUEST', 126);

define ('NO_OVERHAUL_TRACK_CHOICE', 127);

define ('SEARCH_REQUEST', 128);
define ('TRIPS_REQUEST', 129);
define ('INLINE_QUERY_REQUEST_NO_RESULTS_FOUND', 130);

define ('HELP_CHOICE', 131);
define ('ABOUT_CHOICE', 132);
define ('TRIPS_RESULT_CHOICE_MANAGE_TRACK_REQUEST', 133);
define ('SEARCH_RESULT_CHOICE', 134);

define ('CREATE_CONCURRENT_TRACK_CHOICE', 200);
define ('PRIVACY_ON_NOT_OPEN_TRACK_CHOICE', 201);
define ('NAME_ON_NOT_OPEN_TRACK_CHOICE', 202);
define ('TAG_ON_NOT_OPEN_TRACK_CHOICE', 203);
define ('TAG_ON_NOT_EXISTENT_TRACKPOINT', 204);
define ('ILLEGAL_FILE_CHOICE', 205);
define ('UNBOUND_FILE_CHOICE', 206);
define ('SHOW_NOT_OPEN_TRACK_MAP_CHOICE', 207);
define ('END_EMPTY_TRACK_CHOICE', 208);
define ('END_NOT_EXISTENT_TRACK_CHOICE', 209);
define ('CONFIRM_NOT_EXISTENT_TRACK_CHOICE', 210);

define ('OWNER_NOT_SET_INTERNAL_ERROR', 300);
define ('INLINE_OWNER_NOT_SET_INTERNAL_ERROR', 301);
define ('SET_LANGUAGE_CHOICE_INTERNAL_ERROR', 302);
define ('CREATE_TRACK_CHOICE_INTERNAL_ERROR', 303);
define ('SET_TRACK_NAME_CHOICE_INTERNAL_ERROR', 304);
define ('SET_TRACK_PRIVACY_CHOICE_INTERNAL_ERROR', 305);
define ('CREATE_TRACKPOINT_CHOICE_INTERNAL_ERROR', 306);
define ('CREATE_ROADBOOK_ELEMENT_CHOICE_INTERNAL_ERROR', 307); 
define ('SET_TAG_CHOICE_INTERNAL_ERROR', 308);
define ('EDIT_KEY_NOT_SET_INTERNAL_ERROR', 309);
define ('END_TRACK_CHOICE_INTERNAL_ERROR', 310);
define ('SEARCH_REQUEST_INTERNAL_ERROR', 311);
define ('CONFIRM_TRACK_INTERNAL_ERROR', 312);
define ('INLINE_QUERY_REQUEST_INTERNAL_ERROR', 313);
define ('INVALID_CALLBACK_DATA', 314);
define ('DB_INTERNAL_ERROR', 315);
define ('INTERNAL_ERROR', 316);
